version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=mydatabase
    ports:
      - "8000:8000"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: db1234
      MYSQL_USER: user
      MYSQL_PASSWORD: mysql1234
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: