version: '3.8'

services:
  app:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=usoap
      - POSTGRES_PASSWORD=Heslo123
      - POSTGRES_DB=used_sources_database

volumes:
  postgres_data:
