version: '3.8'

services:
  app:
    build: .
    command: python app.py
    environment:
      - MYSQL_HOST=127.0.0.1:8095
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mysql1234
      - MYSQL_DB=db1234
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app